services:
  # run after it starts:
  #
  # export TOKEN=$(dc exec influxdb influx auth create --operator --json | jq -r .token | xargs echo -n)
  # 
  influxdb:
    container_name: influxdb
    hostname: influxdb
    image: influxdb:2.6
    restart: unless-stopped
    command:
      - "--session-length=52560"
    volumes:
      - './config.yml:/etc/influxdb2/config.yml'
    environment:
      - "DOCKER_INFLUXDB_INIT_MODE=setup"
      - "DOCKER_INFLUXDB_INIT_USERNAME=admin"
      - "DOCKER_INFLUXDB_INIT_PASSWORD=password123"
      - "DOCKER_INFLUXDB_INIT_ORG=ngrok"
      - "DOCKER_INFLUXDB_INIT_BUCKET=data"
      - "DOCKER_INFLUXDB_INIT_RETENTION=1d"
    ports:
      - 8086:8086

